extract/urls.py
from django.conf.urls import url
from django.conf.urls.static import static 
from . import views


urlpatterns = [
	url(r'^$', views.list, name='list'),
	url('build_kml', views.build_kml, name='build_kml'),
	url('clear_all', views.clear_all, name='clear_all')
] 

mushrooms/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from djgeojson.views import GeoJSONLayerView

from .models import MushroomSpot
from . import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^extract/', include('extract.urls')),
    url(r'^data.geojson$', GeoJSONLayerView.as_view(model=MushroomSpot, properties=('title', 'description', 'picture_url')), name='data'),
    url(r'^email/.*', views.SendEmail, name='SendEmail')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

extract/models.py
from django.db import models

# Create your models here.

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

mushrooms/models.py
from djgeojson.fields import PolygonField
from django.db import models


class MushroomSpot(models.Model):

    title = models.CharField(max_length=256)
    description = models.TextField()
    picture = models.ImageField()
    geom = PolygonField()

    def __unicode__(self):
        return self.title

    @property
    def picture_url(self):
        return self.picture.url

extract/forms.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        label='Select a file',
        help_text='max. 42 MB',
    )

mushrooms/forms.py
from django import forms
class MessageForm(forms.Form):
    name = forms.CharField(label = 'Address', max_length = 100)
    subject = forms.CharField(label = 'Subject', max_length = 100)
    message = forms.CharField(label = 'Message', max_length = 256)

extract/views.py
from django.shortcuts import render

from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from extract.models import Document
from extract.forms import DocumentForm

from .GenerateKML import KMLifyer
def list(request):

    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            print(type(request.FILES['docfile']))
            for document in request.FILES.getlist('docfile'):


                newdoc = Document(docfile = document)
                newdoc.save()
                print(newdoc.docfile.path)
            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('list'))
    else:
        form = DocumentForm() # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.all()


    # Render list page with the documents and the form
    return render(request, 'list.html', {'documents': documents, 'form': form})
def clear_all(request):
    Document.objects.all().delete()
    documents = Document.objects.all()
    return HttpResponseRedirect(reverse('list'))
    
def build_kml(request):

    documents = Document.objects.all()
    print(documents)
    km = KMLifyer()
    for document in documents:
        print('./' + document.docfile.name)
        km.extract('./' + document.docfile.name)
    kml_string =  km.gen_kml()

    form = DocumentForm()

    response = HttpResponse( content=kml_string, content_type='plain/text')
    response['Content-Disposition'] = 'attachment; filename="images.kml"'

    return response

mushrooms/views.py
from django.shortcuts import render

from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from extract.models import Document
from extract.forms import DocumentForm
from .EmailSender import email
from .forms import MessageForm

image = ''

def SendEmail(request):
    import os 
    global image
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            address = form.cleaned_data['name']
            message = form.cleaned_data['message']
            sub = form.cleaned_data['subject']
        email(address, sub, message, image)
        return HttpResponse('Thanks for using our service')
    else:
        src = request.path[6:] 
        image = os.path.abspath('../Release_1/' + src[10:])
        
        #Get image
        #Get Address
        #email(adress, image)

        msgForm = MessageForm()
        return render(request, 'email.html', {'image':src ,'form':msgForm})

extract/templates/list.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <meta charset="utf-8">
        <meta property="og:image" content="" />
        <link rel= "shortcut icon" type="image/png" href="https://unpkg.com/leaflet@1.2.0/dist/images/marker-icon-2x.png">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
        <title>Upload</title>
    </head>
    <style>
      input[type="file"] {
        display: none;
      }
      .custom-file-upload {
        margin: 0;
        width:10rem;
        cursor: pointer;
        color: #212529;
        background-color: #ffc107;
        border-color: #ffc107;
        display: inline-block;
        font-weight: 400;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        border: 1px solid transparent;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        border-radius: .25rem;
        transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
      }
    </style>
    <script>
      document.getElementById("file").onchange = function() {
        document.getElementById("form").submit();
      }
    </script>

    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top shadow mb-5">
        <a class="navbar-brand align-bottom">
          <img src="https://unpkg.com/leaflet@1.2.0/dist/images/marker-icon-2x.png" width="20px" height="auto" alt="Shroomies">
          <h4 class="d-inline align-bottom">Map that</h4>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle na
          vigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end font-weight-light" id="navbarSupportedContent">
          <ul class="navbar-nav pt-2 pt-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/#">Map</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/extract">Upload</a>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container mt-5 pt-3">
        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url "list" %}" method="post" enctype="multipart/form-data">
          <div class="row justify-content-center mt-4 pt-3">
            <h3>Upload the images you want to display on the map!</h3>
          </div>
          <div class="row mt-3">
            <div class="col-auto">
              <h5 class="mt-4">Step 1:</h5>
              <h5 class="mt-5 pt-2">Step 2:</h5>
            </div>
            <div class="col-auto">
              {% csrf_token %}
              <p>{{ form.non_field_errors }}</p>
              <p class="m-0">
                {{ form.docfile.errors }}
                <!-- {{ form.docfile }} -->
                <input type="file" name="docfile" multiple required id="id_docfile" onchange="javascript:this.form.submit();">
                <label for="id_docfile" class="custom-file-upload">
                  Choose files
                </label>
                <p class="text-center"><small>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</small></p>

              </p>

              <p>
                <!-- <input class="btn btn-warning" type="submit" value="Upload"/> -->
                <button class="btn btn-warning" style="width:10rem;"><a class="text-dark" style="text-decoration:none;" href="{% url 'build_kml'%}">Build KML</a></button>
              </p>
            </div>
            <div class="col mt-3">
              <!-- List of uploaded documents -->
              <div class="row border" style="height: 20rem; overflow-y:scroll">
              {% if documents %}
                  <ul>
                      {% for document in documents %}
                          <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
                      {% endfor %}
                  </ul>
              {% else %}
                  <p class="ml-4 mt-3">No documents chosen.</p>
              {% endif %}
              </div>
              <div class="row justify-content-center mt-2">
                <button class="btn btn-warning text-white" style="width:10rem;"><a class="text-dark" style="text-decoration:none;" href="{% url 'clear_all'%}">Reset</a></button>
              </div>

            </div>
          </div>
        </form>

      </div>
    </body>

</html>

mushrooms/templates/email.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <meta charset="utf-8">
        <meta property="og:image" content="" />
        <link rel= "shortcut icon" type="image/png" href="https://unpkg.com/leaflet@1.2.0/dist/images/marker-icon-2x.png">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
        <title>Send</title>
    </head>


<h3 class = "text-center pt-5" style="margin-top: 5rem">Please Fill the following information out to send this image</h3>
<div class = "text-center">
<p><img style="max-width:300px;" src={{image}}>

  <form action = "" method = "post">
    {% csrf_token %}
    <table align = "center">
    {{ form.as_table }}
    </table>
    <br>
    <input class="btn btn-danger" type ="submit" value = "Submit">
  </form> </p>
</div>
</div>

mushrooms/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="utf-8">
        <meta property="og:image" content="" />

        <link rel= "shortcut icon" type="image/png" href="https://unpkg.com/leaflet@1.2.0/dist/images/marker-icon-2x.png">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css">
    <link rel="stylesheet" href="/static/style.css">
        <title>Map</title>
    </head>

    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top shadow mb-5">
        <a class="navbar-brand align-bottom">
          <img src="https://unpkg.com/leaflet@1.2.0/dist/images/marker-icon-2x.png" width="20px" height="auto" alt="Shroomies">
          <h4 class="d-inline align-bottom">Map that</h4>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle na
          vigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end font-weight-light" id="navbarSupportedContent">
          <ul class="navbar-nav pt-2 pt-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/#">Map</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/extract">Upload</a>
            </li>
          </ul>
        </div>
      </nav>

    <main class="mt-5 pt-3">
        <p class="help">Click on the icon to browse and load local files on the map.
        </p>
        <div id="map" style="width: 100%; height: 100%; display: block;"></div>
    </main>
</body>
<script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
<script src="https://unpkg.com/togeojson@0.16.0"></script>
<script src="https://unpkg.com/leaflet-filelayer@1.2.0"></script>
<script src="/static/index.js"></script>
</html>